### ISSUE TITLE
Update NPM

### ISSUE THREAD

**Issue by vvebvvizard** [jonathantneal/google-fonts-complete#29]
Hi there,

I use your package as a node dependency. But it seems that the NPM package is stuck in 2.1.1, I really need the updated font list in 2.2.2 please :). Could you update NPM with the latest changes?

https://www.npmjs.com/package/google-fonts-complete

Thanks!

**Comment by Stanzilla** [comment]
Yep, new publish would be appreciated

**Comment by gremo** [comment]
Please do! Any update @jonathantneal ?

**Comment by rajdee** [comment]
@vvebvvizard @Stanzilla @gremo Hello, the package has been updated to 2.2.3
