### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by pushbroomsweep** [jonathantneal/google-fonts-complete#30]
Hi, is it possible to update this repository and get a new release. Referencing the discussion from squidfunk/mkdocs-material#5384

**Comment by ThatOtherAndrew** [comment]
Seconded, from https://github.com/squidfunk/mkdocs-material/issues/5798

**Comment by rajdee** [comment]
@pushbroomsweep @ThatOtherAndrew  Hello, the package has been updated to 2.2.3

**Comment by ThatOtherAndrew** [comment]
Fantastic, thank you so much! I'll pass on the news downstream.
